### PR TITLE
Fix META file

### PR DESCRIPTION
**Pull request by samoht**
Note: it seems that the order of elements matters here. /cc @dbuenzli

### CODE REVIEW

**Comment by dsheets** [comment]
Matters how? The previous content built fine for me with ocamlfind 1.6.2.

**Comment by samoht** [comment]
It builds fine, but when you `#require "github-hooks.unix` in a toplevel you have a problem if the META file doesn't list the packages in the right order.

**Comment by dbuenzli** [comment]
What kind of problem ?

**Comment by samoht** [comment]
The `github` package has 2 implementation `github.unix` and `github.jsoo`. `github-hooks` depends on `github`, but `github-hooks.unix` depends on `github.unix`. So `github-hooks-unix` has to lad `github.unix` before trying to load `github-hooks`.

**Pull request merged**
