### PR TITLE
Make github-hooks really independent of unix and update to latest github API

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by dsheets** [comment]
It's really a shame that the jbuild/anti-depopt zealotry is encouraging more top-level opam packages and thus discouraging keeping logical submodules separate. I personally think this trend is silly and was poorly thought out as we have no logical replacement for findlib subpackages at this time. As your PR demonstrates, this new "philosophy" hurts modularity. I don't know what to do about this.

I'm happy with the GitHub library API update and (most of) the Travis changes. Could we keep testing the oldest version that we believe is compatible? So maybe 4.02, 4.04, 4.05?

**Comment by samoht** [comment]
@dsheets the issue with the current split has nothing to do with jbuilder: the `core` library is already using `github-unix` and `conduit-lwt-unix` -- I don't get what we gain by not using Unix directly as well.

**Comment by dsheets** [comment]
The non-unix library does not depend on unix functionality. What do we gain from merging the package and the unix version? The only thing I can see is one fewer opam package and easier publication.

**Comment by samoht** [comment]
> The non-unix library does not depend on unix functionality

Both `github-unix` and `conduit-lwt-unix` which are needed by the core library already needs linking with `unix`. What do you really gain by functorizing over Time/Unix here? What other time implementation do you expect to use?

**Comment by dsheets** [comment]
I think the core library should *not* depend on `github-unix` and `conduit-lwt-unix`. That seems like a current limitation that should be corrected.

I would like the high-level hook server library to be independent of unix so that it can be run in a Mirage unikernel or be mocked out for testing. I thought that was best practice?

**Comment by samoht** [comment]
> I would like the high-level hook server library to be independent of unix so that it can be run in a Mirage unikernel or be mocked out for testing. I thought that was best practice?

That makes a lot of sense but that's currently not the case. I'll see if I can fix this properly.

**Comment by samoht** [comment]
Done: I've functorised the core library over the Github and Http implementation, so it is now unix-free.

**Comment by dsheets** [comment]
Thanks!

**Comment by samoht** [comment]
So 4.05 is broken because nocrypto is not ported to it yet. And 4.02 is broken because:

```
The following dependencies couldn't be met:
  - github-hooks-unix -> cohttp-lwt-unix >= 0.99.0
Your request can't be satisfied:
  - cohttp-lwt-unix>=0.99.0 is not available because your system doesn't comply with ocaml-version >= "4.03.0".
```

Not sure what to do...

**Comment by dsheets** [comment]
I guess we have a minimum requirement of 4.03 so we should test only 4.03 and 4.04 for now.

**Comment by samoht** [comment]
I've removed testing for 4.02 and nocrypto now works on 4.05, so all green!

**Review by dsheets — APPROVED** [review]
Great! Thanks!

**Pull request merged**
